project_id = "agjxgomgkzwdmkjapzhs"

[functions.telemedicine-autoclose]
verify_jwt = false

[functions.daily-webhook]
verify_jwt = false

[functions.telemedicine-guest]
verify_jwt = false

[functions.workflow-run]
verify_jwt = true